### ISSUE TITLE
Scale factor has NaN entries when training my own dataset

### ISSUE THREAD

**Issue by danielkaifeng** [ioangatop/srVAE#1]
I defined my own datasets class in `src/data/datasets.py` and import this class in dataloader, but I met the following problem when run with  
 `python3 main.py --model VAE --network densenet32 --prior RealNVP --dataset  mydataset --img_resize 128`

Thanks for help!

```
Traceback (most recent call last):
  File "main.py", line 119, in <module>
    main()
  File "main.py", line 106, in main
    train_model(args.dataset, args.model, writer)
  File "main.py", line 21, in train_model
    model.module.initialize(train_loader)  
  File "/data3/daniel/srVAE/src/models/vae/vae.py", line 53, in initialize
    self.calculate_elbo(x, output)
  File "/data3/daniel/srVAE/src/models/vae/vae.py", line 89, in calculate_elbo
    log_p_z = self.p_z.log_p(z_q)
  File "/data3/daniel/srVAE/src/modules/priors/realnvp/model/real_nvp.py", line 56, in log_p
    z, sldj = self.forward(x, reverse=False)
  File "/data3/daniel/srVAE/src/modules/priors/realnvp/model/real_nvp.py", line 75, in forward
    x, sldj = self.flows(x, sldj, reverse)
  File "/home/daniel/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/data3/daniel/srVAE/src/modules/priors/realnvp/model/real_nvp.py", line 137, in forward
    x, sldj = coupling(x, sldj, reverse)
  File "/home/daniel/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/data3/daniel/srVAE/src/modules/priors/realnvp/model/coupling_layer.py", line 69, in forward
    raise RuntimeError('Scale factor has NaN entries')

```

**Comment by danielkaifeng** [comment]
It is caused by setting batch_size = 1. When batch_size >= 2, this problem disapper.

**Comment by ioangatop** [comment]
Hi Daniel!

The NaN entries are coming from the RealNVP prior. In general, flow models require good parameter initialisation. Because in my approach, we have a data-driven init, the parameters are adjusted on the first batch. Thus, I believe that for a batch size of 1, we have poor init that they shrink. Please, if you still want to train with batch_size of 1, try to init with a bigger batch size first (change the class attribute `initialize` of `VAE` to grab more data).
